config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get    "posts",          to: "posts#index"
  get    "posts/new",      to: "posts#new",  as: :new_post
  post   "posts",          to: "posts#create"
  get    "posts/:id",      to: "posts#show", as: :post
  get    "posts/:id/edit", to: "posts#edit", as: :edit_post
  patch  "posts/:id",      to: "posts#update"
  delete "posts/:id",      to: "posts#destroy"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :posts
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :subcomments

  validates :comment_content, presence: true, length: { minimum: 1 }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments

  validates :post_content, presence: true
  validates :user_id, presence: true
end

app/models/subcomment.rb
# frozen_string_literal: true

class Subcomment < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  validates :subcomment_content, presence: true, length: { minimum: 1 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts

  validates :name, presence: true, uniqueness: true
end

app/controllers/api/v1/posts_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class PostsController < ApplicationController
      before_action :set_post, only: %i[show update destroy]

      def index
        @posts = Post.all
      end

      def show
        @subcomment = Subcomment.find(params[:id])
      end

      def update
        if @post.update(post_params)
          render :show
        else
          render_error
        end
      end

      def create
        @post = Post.new(post_params)
        if @post.save
          render :show, status: :created
        else
          render_error
        end
      end

      def destroy
        @post.destroy
        head :no_content
      end

      private

      def set_post
        @post = Post.find(params[:id])
      end

      def post_params
        params.require(:post).permit(:post_content, :user_id, :id)
      end

      def render_error
        render json: { errors: @post.errors.full_messages },
               status: :unprocessable_entity
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::API
end

app/controllers/homepages_controller.rb
require 'json'
require 'open-uri'

class HomepagesController < ApplicationController
  def home
    @get_posts = get_posts?
  end

  def get_posts?
    url = 'http://localhost:3000/api/v1/posts'
    posts = URI.open(url).read
    post = JSON.parse(posts)
  end
end

app/controllers/posts_controller.rb
require 'json'
require 'open-uri'

class PostsController < ApplicationController
  before_action :set_get_posts, only: [:show, :edit, :update, :destroy]

  def index
    url = 'http://localhost:3000/api/v1/posts'
    posts = URI.open(url).read
    @post = JSON.parse(posts)
    @posts = Post.all
    @comments = Comment.all
    @subcomments = Subcomment.all

  end

  def show
  end

  def new
    @new_post = Post.new
  end

  def create
    @new_post = Post.new(get_post_params)
    if @new_post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @get_posts.update(get_posts_params)
      redirect_to home_path
    else
      render :edit
    end
  end

  def destroy
    @get_posts.destroy
    redirect_to home_path
  end

  private

  def get_posts_params
    params.require(@posts).permit(:post_content, :user_id, :id)
    params.require(@user).permit(:name)
  end

  def set_get_posts
    @posts = Post.find(params[:id])
    @comments = Comment.find(params[:id])
    @subcomments = Subcomment.find(params[:id])
  end


end

app/views/homepages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My new blog</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags must come first in the head; any other head content must come after these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">
  <link rel="canonical" href="https://getbootstrap.com/docs/3.3/examples/signin/">

  <!-- CSS -->
  <link rel="stylesheet" href="../assets/css/bootstrap.css">
  <link rel="stylesheet" href="../assets/css/datatables.min.css">
  <link rel="stylesheet" href="../assets/css/styles.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">

  <!-- JavaScript -->
  <script src="../assets/js/bootstrap.js">
  </script>
   <script src="../assets/js/datatables.min.js">
  </script>
     <script src="../assets/js/jquery.js">
  </script>



</head>

<%= render 'shared/navbar' %>


<body>

  <table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
      <tr>
          <th>Author</th>
          <th>Content</th>
          <th>Created at</th>
          <th>Options</th>
      </tr>
    </thead>
    <tbody>
      <% @get_posts.each do |post| %>
        <tr>
          <td><%= post["user"] %></td>
          <td><%= post["post_content"] %></td>
          <td><%= post["created_at"] %></td>
          <td><button class="badge rounded-pill text-bg-primary"><i class="bi bi-eye"></i></button>
            <button class="badge rounded-pill text-bg-primary"><i class="bi bi-pencil"></i></button>
            <button class="badge rounded-pill text-bg-primary"><i class="bi bi-pencil"></i></button>
            <button class="badge rounded-pill text-bg-primary"><i class="bi bi-eraser"></i></button>
          </td>
        </tr>
      <% end %>
        </tbody>
  </table>

  <script type="text/javascript">
  $(document).ready(function () {
    $('#example').DataTable();
  });
  </script>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags must come first in the head; any other head content must come after these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/3.3/examples/signin/">

    <title>Signin Template for Bootstrap</title>
    <!-- CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
        integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <!-- JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
        integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ"
        crossorigin="anonymous"></script>

    <!-- Local fallback -->

</head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>

</html>

app/views/posts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My new blog</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags must come first in the head; any other head content must come after these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">
  <link rel="canonical" href="https://getbootstrap.com/docs/3.3/examples/signin/">

  <!-- CSS -->
  <link rel="stylesheet" href="../assets/css/bootstrap.css">
  <link rel="stylesheet" href="../assets/css/datatables.min.css">
  <link rel="stylesheet" href="../assets/css/styles.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">

  <!-- JavaScript -->
  <script src="../assets/js/bootstrap.js">
  </script>
   <script src="../assets/js/datatables.min.js">
  </script>
     <script src="../assets/js/jquery.js">
  </script>



</head>

<%= render 'shared/navbar' %>


<body>

  <table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
      <tr>
          <th>Author</th>
          <th>Content</th>
          <th>Created at</th>
          <th>Options</th>
      </tr>
    </thead>
    <tbody>
      <% @get_posts.each do |post| %>
        <tr>
          <td><%= post["user"] %></td>
          <td><%= post["post_content"] %></td>
          <td><%= post["created_at"] %></td>
          <td>
            <button class="badge rounded-pill text-bg-primary"> <%= link_to "", "/show_path#{@post.find(params["id"])}" %><i class="bi bi-eye"></i></button>
            <button class="badge rounded-pill text-bg-primary"><i class="bi bi-pencil"></i></button>
            <button class="badge rounded-pill text-bg-primary"><i class="bi bi-pencil"></i></button>
            <button class="badge rounded-pill text-bg-primary"><i class="bi bi-eraser"></i></button>


          </td>
        </tr>
      <% end %>
        </tbody>
  </table>

  <script type="text/javascript">
  $(document).ready(function () {
    $('#example').DataTable();
  });
  </script>

</body>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>My new blog</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags must come first in the head; any other head content must come after these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">
  <link rel="canonical" href="https://getbootstrap.com/docs/3.3/examples/signin/">

  <!-- CSS -->
  <link rel="stylesheet" href="../assets/css/bootstrap.css">
  <link rel="stylesheet" href="../assets/css/datatables.min.css">
  <link rel="stylesheet" href="../assets/css/styles.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">

  <!-- JavaScript -->
  <script src="../assets/js/bootstrap.js">
  </script>
  <script src="../assets/js/datatables.min.js">
  </script>
  <script src="../assets/js/jquery.js">
  </script>

</head>

<%= render 'shared/navbar' %>

<body>

  <table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
      <tr>
        <th>Author</th>
        <th>Content</th>
        <th>Created at</th>
        <th>Options</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
      <tr>
        <td><%= post["user"] %></td>
        <td><%= post["post_content"] %></td>
        <td><%= post["created_at"] %></td>
        <td>
          <button class="badge rounded-pill text-bg-primary"><%= link_to "", post_path(@posts) %><i class="bi bi-eye"></i></button>
          <button class="badge rounded-pill text-bg-primary"><%= link_to "", post_path(@posts) %><i class="bi bi-pencil"></i></button>
          <button class="badge rounded-pill text-bg-primary"><%= link_to "", post_path(@posts) %><i class="bi bi-eraser"></i></button>

        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <script type="text/javascript">
    $(document).ready(function() {
      $('#example').DataTable();
    });
  </script>

</body>

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Post</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags must come first in the head; any other head content must come after these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">
  <link rel="canonical" href="https://getbootstrap.com/docs/3.3/examples/signin/">

  <!-- CSS -->
  <link rel="stylesheet" href="../assets/css/bootstrap.css">
  <link rel="stylesheet" href="../assets/css/datatables.min.css">
  <link rel="stylesheet" href="../assets/css/styles.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">

  <!-- JavaScript -->
  <script src="../assets/js/bootstrap.js">
  </script>
  <script src="../assets/js/datatables.min.js">
  </script>
  <script src="../assets/js/jquery.js">
  </script>

</head>

<%= render 'shared/navbar' %>

<div class="container p-3 bg-light border mt-2 main-title" style="width: 40rem; border-radius: 25px;">
  <h2 class="main-title ">Add new post</h2>
  <div class="row">
    <div class="col-12 d-flex justify-content-center text-center">
      <div class="data-card2">

        <%= simple_form_for(@new_post) do |f| %>
        <div class="form-inputs" style="width: 20rem; border-radius: 25px;">
          <div class="flat-form2">
            <%= f.label "Your Name" %>
            <%= f.input :user, label: false, placeholder: "What is your name?", :input_html => { class: "form-nice-class" } %>
          </div>

          <div class="flat-form2">
            <%= f.label "Text" %>
            <%= f.input :post_content, label: false, placeholder: "You can type in here...", :input_html => { class: "form-nice-class" } %>
          </div>
        </div>
        <% end %>

        <div class="form-actions">
          <%= link_to 'Add Post', posts_path, method: :post, class: 'btn btn-outline-dark btn-block w-100 p-2 border'%>
        </div>

                <div class="form-actions">
          <%= link_to 'Homepage', posts_path, class: 'btn btn-outline-dark btn-block w-100 p-2 border'%>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Post</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags must come first in the head; any other head content must come after these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">
  <link rel="canonical" href="https://getbootstrap.com/docs/3.3/examples/signin/">

  <!-- CSS -->
  <link rel="stylesheet" href="../assets/css/bootstrap.css">
  <link rel="stylesheet" href="../assets/css/datatables.min.css">
  <link rel="stylesheet" href="../assets/css/styles.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">

  <!-- JavaScript -->
  <script src="../assets/js/bootstrap.js">
  </script>
  <script src="../assets/js/datatables.min.js">
  </script>
  <script src="../assets/js/jquery.js">
  </script>

</head>

<%= render 'shared/navbar' %>

<h1><%= @posts["user"] %></h1>
<h2><%= @posts["post_content"] %></h2>
<h6><%= @posts["created_at"].strftime('%F') %></h6>

<h3><%= @comments["comment_content"] %></h3>
<h2><%= @comments["user"] %></h2>
<h6><%= @posts["created_at"].strftime('%F') %></h6>

<h3><%= @subcomments["subcomment_content"] %></h3>
<h2><%= @subcomments["user"] %></h2>
<h6><%= @posts["created_at"].strftime('%F') %></h6>

app/views/shared/_navbar.html.erb
<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" href="../assets/css/bootstrap.css">
  <link rel="stylesheet" href="../assets/css/datatables.min.css">
  <link rel="stylesheet" href="../assets/css/styles.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">

</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <ul class="navbar-nav ul">
          <li class=" li nav-item">
            <%= link_to 'Homepage', posts_path, class: 'btn btn-outline-dark btn-block w-100 p-2 border'%>
          </li>
        </ul>
        <ul class="ul navbar-nav">
          <li class=" li nav-item">
            <%= link_to 'New Post', new_post_path, class: 'btn btn-outline-dark btn-block w-100 p-2 border'%>
          </li>
        </ul>
      </div>
      </nav>
</body>